/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.generarReporte;
import Clases.sesionUsuario;
import baseDatos.baseProductos.productCrud;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author decab
 */
public class tablaUI extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla;
    private headerMinimalista header;
    private navegacionHeader navegar;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tablaUI.class.getName());

    /**
     * Creates new form tablaUI
     */
    public tablaUI() {
        initComponents();
        adminProd.setVisible(false);
        setLocationRelativeTo(null);
        getContentPane().setLayout(new BorderLayout());
        header = new headerMinimalista(this);
        navegar = new navegacionHeader(this);
        config();
        configurarTabla();
        cargarDatosTabla();
        calcularTotal();
        permisosAdmin();
        
        revalidate();
        repaint();
    }
    private void config(){
        JPanel headerContainer = new JPanel(new BorderLayout());//contenedor de los heades
        headerContainer.add(header, BorderLayout.NORTH);  // X y —
        headerContainer.add(navegar, BorderLayout.SOUTH);   // Botones

        getContentPane().add(headerContainer, BorderLayout.NORTH);
        getContentPane().add(bckgrnd, BorderLayout.CENTER);
    }
    @Override
    public void dispose(){ //cierra bd al cerrar la ventana
        productCrud.closeConnection();
        super.dispose();
    }
    private void configurarTabla() {
    modeloTabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Hacer la tabla no editable
        }
    };
    
    // Definir columnas
    modeloTabla.addColumn("NOMBRE");
    modeloTabla.addColumn("DESCRIPCION");
    modeloTabla.addColumn("CANTIDAD");
    modeloTabla.addColumn("PRECIO DE VENTA");
    modeloTabla.addColumn("TOTAL");
    
    tablaProductos.setModel(modeloTabla);
    }
    public void cargarDatosTabla(){
        productCrud.initDatabase(); //INICIAR BASE DE DATOS
        productCrud.leerMisProductos(modeloTabla);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bckgrnd = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        borrarBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        totalCalculado = new javax.swing.JLabel();
        adminProd = new javax.swing.JButton();
        reporteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bckgrnd.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        tablaProductos.setBackground(new java.awt.Color(255, 255, 255));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Cantidad", "Precio de venta", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VENTAS REALIZADAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(275, 275, 275))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("En esta seccion se muestran las ventas realizadas por el usuario.");

        borrarBtn.setText("BORRAR");
        borrarBtn.addActionListener(this::borrarBtnActionPerformed);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOTAL DE TODOS LOS PRODUCTOS: $");

        totalCalculado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalCalculado.setForeground(new java.awt.Color(255, 255, 255));
        totalCalculado.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalCalculado, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalCalculado))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        adminProd.setText("VER TODOS LOS PRODUCTOS");
        adminProd.addActionListener(this::adminProdActionPerformed);

        reporteBtn.setText("CREAR REPORTE");
        reporteBtn.addActionListener(this::reporteBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 197, Short.MAX_VALUE)
                        .addComponent(adminProd, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reporteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(borrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarBtn)
                    .addComponent(adminProd)
                    .addComponent(reporteBtn))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bckgrndLayout = new javax.swing.GroupLayout(bckgrnd);
        bckgrnd.setLayout(bckgrndLayout);
        bckgrndLayout.setHorizontalGroup(
            bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bckgrndLayout.setVerticalGroup(
            bckgrndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bckgrndLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckgrnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBtnActionPerformed
        int filaSeleccionada = tablaProductos.getSelectedRow();
        try {
            if (filaSeleccionada >= 0){ //borrar por fila seleccionada
                if (JOptionPane.showConfirmDialog(null,
                        "¿Quieres eliminar este producto?",
                        "Confirmar",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    productCrud.borrarProducto(modeloTabla.getValueAt(filaSeleccionada, 0).toString());
                    cargarDatosTabla();
                    calcularTotal(); //vuelve a calcular el total
                }
            }else{
                JOptionPane.showMessageDialog(null, "Selecciona una fila", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error general", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_borrarBtnActionPerformed

    private void permisosAdmin(){
        sesionUsuario sesion = sesionUsuario.getInstance();
        if (sesion.isEsAdmin()) { //funciones de administrador
            adminProd.setVisible(true);
        }
    }
    private void adminProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminProdActionPerformed
        allProducts pr = new allProducts();
        pr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminProdActionPerformed

    private void reporteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteBtnActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(null,
                        "¿Quieres crear un nuevo reporte de estas ventas?",
                        "Confirmar",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String nomDoc = JOptionPane.showInputDialog(null,
                        "Ingrese el nombre del documento",
                        "Nombre del documento",
                        JOptionPane.QUESTION_MESSAGE);
                if (nomDoc.equals("")){nomDoc = "Reporte_";}
                    generarReporte.crearReporte(modeloTabla, nomDoc+"_", sesionUsuario.getInstance().getNombre());
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error general", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_reporteBtnActionPerformed
    private void calcularTotal(){ //calcula el total y lo pone en el texto
        try {
            double total_fin = 0;
            int filas = modeloTabla.getRowCount();
            if (filas >= 1){ 
                for (int i=0;i<filas;i++){
                total_fin += Double.parseDouble(modeloTabla.getValueAt(i, 4).toString());
                }
            }
            totalCalculado.setText(String.valueOf(total_fin));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al calcular el total", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tablaUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminProd;
    private javax.swing.JPanel bckgrnd;
    private javax.swing.JButton borrarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reporteBtn;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JLabel totalCalculado;
    // End of variables declaration//GEN-END:variables
}
